import 'package:mute_mate/Model/SignPhrase.dart';

/// The full bilingual Arabic-first sign language knowledge base.
///
/// Asset paths follow the pattern:
///   signs: assets/signs/<id>.gif
///   audio: assets/audio/<id>.mp3
///
/// Add actual GIF / MP3 files to those folders and register them in pubspec.yaml.
class SignLanguageDataset {
  SignLanguageDataset._();

  static const List<SignPhrase> allPhrases = [
    // ──────────────────────────────────────────
    // MEDICAL — طبي
    // ──────────────────────────────────────────
    SignPhrase(
      id: 'need_doctor',
      arabicText: 'أحتاج إلى طبيب',
      englishText: 'I need a doctor',
      keywords: ['طبيب', 'دكتور', 'أحتاج'],
      signAssetPath: 'lib/Assets/Images/GIF1.gif',
      audioAssetPath: 'assets/audio/need_doctor.mp3',
      category: PhraseCategory.medical,
    ),
    SignPhrase(
      id: 'in_pain',
      arabicText: 'أنا في ألم',
      englishText: 'I am in pain',
      keywords: ['ألم', 'يؤلم', 'وجع', 'مؤلم'],
      signAssetPath: 'assets/signs/in_pain.gif',
      audioAssetPath: 'assets/audio/in_pain.mp3',
      category: PhraseCategory.medical,
    ),
    SignPhrase(
      id: 'where_hospital',
      arabicText: 'أين المستشفى؟',
      englishText: 'Where is the hospital?',
      keywords: ['مستشفى', 'أين', 'مكان'],
      signAssetPath: 'assets/signs/where_hospital.gif',
      audioAssetPath: 'assets/audio/where_hospital.mp3',
      category: PhraseCategory.medical,
    ),
    SignPhrase(
      id: 'i_am_sick',
      arabicText: 'أنا مريض',
      englishText: 'I am sick',
      keywords: ['مريض', 'مرض', 'تعبان'],
      signAssetPath: 'assets/signs/i_am_sick.gif',
      audioAssetPath: 'assets/audio/i_am_sick.mp3',
      category: PhraseCategory.medical,
    ),
    SignPhrase(
      id: 'allergy',
      arabicText: 'لدي حساسية',
      englishText: 'I have an allergy',
      keywords: ['حساسية', 'تحسس', 'لدي'],
      signAssetPath: 'assets/signs/allergy.gif',
      audioAssetPath: 'assets/audio/allergy.mp3',
      category: PhraseCategory.medical,
    ),
    SignPhrase(
      id: 'need_medicine',
      arabicText: 'أحتاج دواء',
      englishText: 'I need medicine',
      keywords: ['دواء', 'دواءً', 'علاج', 'حبوب'],
      signAssetPath: 'assets/signs/need_medicine.gif',
      audioAssetPath: 'assets/audio/need_medicine.mp3',
      category: PhraseCategory.medical,
    ),
    SignPhrase(
      id: 'where_pharmacy',
      arabicText: 'أين الصيدلية؟',
      englishText: 'Where is the pharmacy?',
      keywords: ['صيدلية', 'أين', 'دواء'],
      signAssetPath: 'assets/signs/where_pharmacy.gif',
      audioAssetPath: 'assets/audio/where_pharmacy.mp3',
      category: PhraseCategory.medical,
    ),
    SignPhrase(
      id: 'need_ambulance',
      arabicText: 'أحتاج سيارة إسعاف',
      englishText: 'I need an ambulance',
      keywords: ['إسعاف', 'سيارة', 'أحتاج'],
      signAssetPath: 'assets/signs/need_ambulance.gif',
      audioAssetPath: 'assets/audio/need_ambulance.mp3',
      category: PhraseCategory.medical,
    ),
    SignPhrase(
      id: 'feel_dizzy',
      arabicText: 'أشعر بدوار',
      englishText: 'I feel dizzy',
      keywords: ['دوار', 'دوخة', 'أشعر', 'يدور'],
      signAssetPath: 'assets/signs/feel_dizzy.gif',
      audioAssetPath: 'assets/audio/feel_dizzy.mp3',
      category: PhraseCategory.medical,
    ),
    SignPhrase(
      id: 'high_pressure',
      arabicText: 'ضغطي مرتفع',
      englishText: 'My blood pressure is high',
      keywords: ['ضغط', 'مرتفع', 'دم'],
      signAssetPath: 'assets/signs/high_pressure.gif',
      audioAssetPath: 'assets/audio/high_pressure.mp3',
      category: PhraseCategory.medical,
    ),

    // ──────────────────────────────────────────
    // GREETINGS — تحيات
    // ──────────────────────────────────────────
    SignPhrase(
      id: 'hello',
      arabicText: 'مرحباً',
      englishText: 'Hello',
      keywords: ['مرحبا', 'أهلا', 'السلام', 'هلا'],
      signAssetPath: 'assets/signs/hello.gif',
      audioAssetPath: 'assets/audio/hello.mp3',
      category: PhraseCategory.greeting,
    ),
    SignPhrase(
      id: 'thank_you',
      arabicText: 'شكراً جزيلاً',
      englishText: 'Thank you',
      keywords: ['شكرا', 'شكراً', 'ممنون', 'متشكر'],
      signAssetPath: 'assets/signs/thank_you.gif',
      audioAssetPath: 'assets/audio/thank_you.mp3',
      category: PhraseCategory.greeting,
    ),
    SignPhrase(
      id: 'please',
      arabicText: 'من فضلك',
      englishText: 'Please',
      keywords: ['فضلك', 'رجاء', 'لو سمحت'],
      signAssetPath: 'assets/signs/please.gif',
      audioAssetPath: 'assets/audio/please.mp3',
      category: PhraseCategory.greeting,
    ),
    SignPhrase(
      id: 'sorry',
      arabicText: 'آسف / عفواً',
      englishText: 'Sorry / Excuse me',
      keywords: ['آسف', 'عفو', 'معلش', 'اسف'],
      signAssetPath: 'assets/signs/sorry.gif',
      audioAssetPath: 'assets/audio/sorry.mp3',
      category: PhraseCategory.greeting,
    ),
    SignPhrase(
      id: 'goodbye',
      arabicText: 'مع السلامة',
      englishText: 'Goodbye',
      keywords: ['سلامة', 'وداع', 'باي', 'إلى اللقاء'],
      signAssetPath: 'assets/signs/goodbye.gif',
      audioAssetPath: 'assets/audio/goodbye.mp3',
      category: PhraseCategory.greeting,
    ),
    SignPhrase(
      id: 'good_morning',
      arabicText: 'صباح الخير',
      englishText: 'Good morning',
      keywords: ['صباح', 'الخير', 'صباحية'],
      signAssetPath: 'assets/signs/good_morning.gif',
      audioAssetPath: 'assets/audio/good_morning.mp3',
      category: PhraseCategory.greeting,
    ),
    SignPhrase(
      id: 'good_evening',
      arabicText: 'مساء الخير',
      englishText: 'Good evening',
      keywords: ['مساء', 'الخير', 'مسائية'],
      signAssetPath: 'assets/signs/good_evening.gif',
      audioAssetPath: 'assets/audio/good_evening.mp3',
      category: PhraseCategory.greeting,
    ),
    SignPhrase(
      id: 'how_are_you',
      arabicText: 'كيف حالك؟',
      englishText: 'How are you?',
      keywords: ['كيف', 'حال', 'أحوال'],
      signAssetPath: 'assets/signs/how_are_you.gif',
      audioAssetPath: 'assets/audio/how_are_you.mp3',
      category: PhraseCategory.greeting,
    ),
    SignPhrase(
      id: 'i_am_fine',
      arabicText: 'أنا بخير',
      englishText: 'I am fine',
      keywords: ['بخير', 'تمام', 'كويس', 'أنا'],
      signAssetPath: 'assets/signs/i_am_fine.gif',
      audioAssetPath: 'assets/audio/i_am_fine.mp3',
      category: PhraseCategory.greeting,
    ),
    SignPhrase(
      id: 'my_name_is',
      arabicText: 'اسمي...',
      englishText: 'My name is...',
      keywords: ['اسمي', 'اسم', 'يسمى'],
      signAssetPath: 'assets/signs/my_name_is.gif',
      audioAssetPath: 'assets/audio/my_name_is.mp3',
      category: PhraseCategory.greeting,
    ),

    // ──────────────────────────────────────────
    // EMERGENCY — طوارئ
    // ──────────────────────────────────────────
    SignPhrase(
      id: 'help_me',
      arabicText: 'ساعدني',
      englishText: 'Help me',
      keywords: ['ساعدني', 'مساعدة', 'نجدة', 'أنقذني'],
      signAssetPath: 'assets/signs/help_me.gif',
      audioAssetPath: 'assets/audio/help_me.mp3',
      category: PhraseCategory.emergency,
    ),
    SignPhrase(
      id: 'call_ambulance',
      arabicText: 'اتصل بالإسعاف',
      englishText: 'Call the ambulance',
      keywords: ['إسعاف', 'اتصل', 'استدعي'],
      signAssetPath: 'assets/signs/call_ambulance.gif',
      audioAssetPath: 'assets/audio/call_ambulance.mp3',
      category: PhraseCategory.emergency,
    ),
    SignPhrase(
      id: 'call_police',
      arabicText: 'اتصل بالشرطة',
      englishText: 'Call the police',
      keywords: ['شرطة', 'اتصل', 'بوليس'],
      signAssetPath: 'assets/signs/call_police.gif',
      audioAssetPath: 'assets/audio/call_police.mp3',
      category: PhraseCategory.emergency,
    ),
    SignPhrase(
      id: 'accident',
      arabicText: 'هناك حادث',
      englishText: 'There is an accident',
      keywords: ['حادث', 'اصطدام', 'هناك'],
      signAssetPath: 'assets/signs/accident.gif',
      audioAssetPath: 'assets/audio/accident.mp3',
      category: PhraseCategory.emergency,
    ),
    SignPhrase(
      id: 'fire',
      arabicText: 'هناك حريق',
      englishText: 'There is a fire',
      keywords: ['حريق', 'نار', 'حرق'],
      signAssetPath: 'assets/signs/fire.gif',
      audioAssetPath: 'assets/audio/fire.mp3',
      category: PhraseCategory.emergency,
    ),
    SignPhrase(
      id: 'i_am_lost',
      arabicText: 'أنا ضائع',
      englishText: 'I am lost',
      keywords: ['ضائع', 'تهت', 'مكان'],
      signAssetPath: 'assets/signs/i_am_lost.gif',
      audioAssetPath: 'assets/audio/i_am_lost.mp3',
      category: PhraseCategory.emergency,
    ),
    SignPhrase(
      id: 'in_danger',
      arabicText: 'أنا في خطر',
      englishText: 'I am in danger',
      keywords: ['خطر', 'خطير', 'أنا'],
      signAssetPath: 'assets/signs/in_danger.gif',
      audioAssetPath: 'assets/audio/in_danger.mp3',
      category: PhraseCategory.emergency,
    ),
    SignPhrase(
      id: 'drowning',
      arabicText: 'أنا أغرق',
      englishText: 'I am drowning',
      keywords: ['أغرق', 'غرق', 'ماء'],
      signAssetPath: 'assets/signs/drowning.gif',
      audioAssetPath: 'assets/audio/drowning.mp3',
      category: PhraseCategory.emergency,
    ),

    // ──────────────────────────────────────────
    // DAILY — يومي
    // ──────────────────────────────────────────
    SignPhrase(
      id: 'yes',
      arabicText: 'نعم',
      englishText: 'Yes',
      keywords: ['نعم', 'أيوه', 'صحيح', 'موافق'],
      signAssetPath: 'assets/signs/yes.gif',
      audioAssetPath: 'assets/audio/yes.mp3',
      category: PhraseCategory.daily,
    ),
    SignPhrase(
      id: 'no',
      arabicText: 'لا',
      englishText: 'No',
      keywords: ['لا', 'مش', 'مو', 'رفض'],
      signAssetPath: 'assets/signs/no.gif',
      audioAssetPath: 'assets/audio/no.mp3',
      category: PhraseCategory.daily,
    ),
    SignPhrase(
      id: 'dont_understand',
      arabicText: 'لم أفهم',
      englishText: 'I don\'t understand',
      keywords: ['لم', 'أفهم', 'مش فاهم', 'ما فهمت'],
      signAssetPath: 'assets/signs/dont_understand.gif',
      audioAssetPath: 'assets/audio/dont_understand.mp3',
      category: PhraseCategory.daily,
    ),
    SignPhrase(
      id: 'repeat',
      arabicText: 'هل يمكنك الإعادة؟',
      englishText: 'Can you repeat?',
      keywords: ['إعادة', 'أعد', 'كرر', 'مرة ثانية'],
      signAssetPath: 'assets/signs/repeat.gif',
      audioAssetPath: 'assets/audio/repeat.mp3',
      category: PhraseCategory.daily,
    ),
    SignPhrase(
      id: 'speak_slowly',
      arabicText: 'تكلم ببطء',
      englishText: 'Speak slowly',
      keywords: ['ببطء', 'بطيء', 'آهسته', 'بهدوء'],
      signAssetPath: 'assets/signs/speak_slowly.gif',
      audioAssetPath: 'assets/audio/speak_slowly.mp3',
      category: PhraseCategory.daily,
    ),
    SignPhrase(
      id: 'how_much',
      arabicText: 'كم السعر؟',
      englishText: 'How much does it cost?',
      keywords: ['سعر', 'كم', 'ثمن', 'قيمة'],
      signAssetPath: 'assets/signs/how_much.gif',
      audioAssetPath: 'assets/audio/how_much.mp3',
      category: PhraseCategory.daily,
    ),
    SignPhrase(
      id: 'bathroom',
      arabicText: 'أين الحمام؟',
      englishText: 'Where is the bathroom?',
      keywords: ['حمام', 'دورة مياه', 'أين'],
      signAssetPath: 'assets/signs/bathroom.gif',
      audioAssetPath: 'assets/audio/bathroom.mp3',
      category: PhraseCategory.daily,
    ),
    SignPhrase(
      id: 'hungry',
      arabicText: 'أنا جائع',
      englishText: 'I am hungry',
      keywords: ['جائع', 'جوعان', 'أكل'],
      signAssetPath: 'assets/signs/hungry.gif',
      audioAssetPath: 'assets/audio/hungry.mp3',
      category: PhraseCategory.daily,
    ),
    SignPhrase(
      id: 'thirsty',
      arabicText: 'أنا عطشان',
      englishText: 'I am thirsty',
      keywords: ['عطشان', 'عطش', 'ماء', 'شرب'],
      signAssetPath: 'assets/signs/thirsty.gif',
      audioAssetPath: 'assets/audio/thirsty.mp3',
      category: PhraseCategory.daily,
    ),
    SignPhrase(
      id: 'i_want_to_go',
      arabicText: 'أريد الذهاب إلى...',
      englishText: 'I want to go to...',
      keywords: ['أريد', 'الذهاب', 'أذهب', 'روح'],
      signAssetPath: 'assets/signs/i_want_to_go.gif',
      audioAssetPath: 'assets/audio/i_want_to_go.mp3',
      category: PhraseCategory.daily,
    ),
    SignPhrase(
      id: 'water',
      arabicText: 'ماء من فضلك',
      englishText: 'Water please',
      keywords: ['ماء', 'مياه', 'شرب'],
      signAssetPath: 'assets/signs/water.gif',
      audioAssetPath: 'assets/audio/water.mp3',
      category: PhraseCategory.daily,
    ),

    // ──────────────────────────────────────────
    // EMOTIONS — مشاعر
    // ──────────────────────────────────────────
    SignPhrase(
      id: 'happy',
      arabicText: 'أنا سعيد',
      englishText: 'I am happy',
      keywords: ['سعيد', 'سعادة', 'فرحان', 'مبسوط'],
      signAssetPath: 'assets/signs/happy.gif',
      audioAssetPath: 'assets/audio/happy.mp3',
      category: PhraseCategory.emotion,
    ),
    SignPhrase(
      id: 'sad',
      arabicText: 'أنا حزين',
      englishText: 'I am sad',
      keywords: ['حزين', 'حزن', 'زعلان', 'مكتئب'],
      signAssetPath: 'assets/signs/sad.gif',
      audioAssetPath: 'assets/audio/sad.mp3',
      category: PhraseCategory.emotion,
    ),
    SignPhrase(
      id: 'afraid',
      arabicText: 'أنا خائف',
      englishText: 'I am afraid',
      keywords: ['خائف', 'خوف', 'خايف'],
      signAssetPath: 'assets/signs/afraid.gif',
      audioAssetPath: 'assets/audio/afraid.mp3',
      category: PhraseCategory.emotion,
    ),
    SignPhrase(
      id: 'tired',
      arabicText: 'أنا متعب',
      englishText: 'I am tired',
      keywords: ['متعب', 'تعب', 'مرهق', 'إرهاق'],
      signAssetPath: 'assets/signs/tired.gif',
      audioAssetPath: 'assets/audio/tired.mp3',
      category: PhraseCategory.emotion,
    ),
    SignPhrase(
      id: 'angry',
      arabicText: 'أنا غاضب',
      englishText: 'I am angry',
      keywords: ['غاضب', 'غضب', 'زعلان', 'عصبي'],
      signAssetPath: 'assets/signs/angry.gif',
      audioAssetPath: 'assets/audio/angry.mp3',
      category: PhraseCategory.emotion,
    ),
    SignPhrase(
      id: 'worried',
      arabicText: 'أنا قلق',
      englishText: 'I am worried',
      keywords: ['قلق', 'قلقان', 'توتر', 'متوتر'],
      signAssetPath: 'assets/signs/worried.gif',
      audioAssetPath: 'assets/audio/worried.mp3',
      category: PhraseCategory.emotion,
    ),
    SignPhrase(
      id: 'need_help',
      arabicText: 'أحتاج مساعدة',
      englishText: 'I need help',
      keywords: ['مساعدة', 'أحتاج', 'مساعد'],
      signAssetPath: 'assets/signs/need_help.gif',
      audioAssetPath: 'assets/audio/need_help.mp3',
      category: PhraseCategory.emotion,
    ),
    SignPhrase(
      id: 'lonely',
      arabicText: 'أنا وحيد',
      englishText: 'I am lonely',
      keywords: ['وحيد', 'وحده', 'وحدتي'],
      signAssetPath: 'assets/signs/lonely.gif',
      audioAssetPath: 'assets/audio/lonely.mp3',
      category: PhraseCategory.emotion,
    ),
  ];

  /// Returns phrases filtered by [category]. Returns all if [category] is null.
  static List<SignPhrase> byCategory(PhraseCategory? category) {
    if (category == null) return allPhrases;
    return allPhrases.where((p) => p.category == category).toList();
  }
}
