# Generated by Django 6.0.6 on 2026-06-13 14:09

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MuteUser',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('us_id', models.CharField(help_text='Legacy UUID identifier used by the API views and JWT tokens', max_length=100, unique=True)),
                ('us_full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('us_email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('us_phone_number', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('us_password', models.CharField(max_length=255, verbose_name='Password (hashed)')),
                ('us_user_type', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('admin', 'Admin')], default='standard', max_length=50, verbose_name='User Type')),
                ('us_points_balance', models.IntegerField(default=0, verbose_name='Points Balance')),
                ('us_daily_translation_count', models.IntegerField(default=0, verbose_name='Daily Translation Count')),
                ('us_last_reset_date', models.DateTimeField(blank=True, null=True, verbose_name='Last Reset Date')),
                ('us_subscription_plan_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subscription Plan ID')),
                ('us_is_authenticated', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mute-Mate User',
                'verbose_name_plural': 'Mute-Mate Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
    ]
